### ISSUE TITLE
HelloDecafTest   Cannot find coffee file

### ISSUE THREAD

**Issue by mrt123** [limadelic/decaf#8]
Hi,

I have followed: https://github.com/limadelic/decaf/issues/5
and changed my `COMMAND_PATTERN=decaf %p`   (running on OSX)

Everything else is the same as in https://github.com/limadelic/decaf/wiki/Hello-Decaf

When running http://localhost:8080/HelloDecafTest?test i get: 
Could not complete testing: fitnesse.slim.SlimError: Error SLiM server died before a connection could be established. env: coffee: No such file or directory

**Comment by noamtcohen** [comment]
@mrt123  where you able to resolve this?

**Comment by mrt123** [comment]
@noamtcohen  issue is still there for me

**Comment by noamtcohen** [comment]
This is how I proceeded:
After install decaf in the directory where fitnesse.jar is (not globally) 
on `http://localhost:8080/root?edit` I made this change:

```
!define TEST_SYSTEM {slim}
!define COMMAND_PATTERN {node node_modules/decaf/lib/decaf %p}
```

so now I'm getting a different error that the class I'm try to test was not found: `Cannot find greeter`

**Comment by msuarz** [comment]
sorry i am late to the party ... i've been in NY on holidays ... i'll check this as soon as possible

**Comment by noamtcohen** [comment]
If I change the example and rename from greeter.coffee:

```
class @Greeter
  hello: (who) -> "Hello #{who}!"
```

to greetet.js:

```
function Greeter(){

}
```

I'm green on the imports but I get these errors:

```
TypeError: Cannot read property 'Greeter' of undefined
TypeError: Cannot read property 'sut' of undefined
```

**Comment by noamtcohen** [comment]
@mrt123 I put together a demo, please download the zip and see the readme. let me know if this works for you.
https://github.com/noamtcohen/FitnesseWithCoffee

**Comment by mrt123** [comment]
@noamtcohen thanks , this worked

**Comment by noamtcohen** [comment]
@mrt123, regarding you question about protractor. protractor is build on top [WebDriverJs](https://github.com/SeleniumHQ/selenium/wiki/WebDriverJs) so you could just use WebDriverJs from within your node test suite. FitNesee runs test files, protractor runs test files. What you could do is invoke protractor from your node test file (via fork or spawn) and then parse the output of protractor and send it back to FitNesse. I'm working on a project to support this kind of functionality (but not specific to protractor):  [SlimJS](https://github.com/noamtcohen/SlimJS). Please post your questions on the SlimJS repo, Cheers.

**Comment by msuarz** [comment]
Hi there ... i finally got some time to test this ... this was working for me on a mac ....

!define TEST_SYSTEM {slim}
!define COMMAND_PATTERN {decaf %p}
!path fixtures

|import|
|greeter|

|script|Greeter|
|check|hello|Decaf|Hello Decaf!|

**Comment by noamtcohen** [comment]
@msuarz thanks you checking this for us.
I've started a new project [SlimJS](https://github.com/noamtcohen/SlimJS). It an async nodejs slim server. This is better for my use case since all of my javascript code is written in javascript, I don't see a reason to learn coffeescript and I need it to asynchronous.
Thanks again for helping out.

**Comment by msuarz** [comment]
no worries the hate on coffeescript is strong out there :) ... i've learned to ignore it ... a couple of things ...

. decaf should work the same for js than for coffee ... 'cos coffee is js 
. good luck with the async implementation ... i've though bout it a few times ... fitnesse/slim is not going to help u ... u end up with async steps but they don't nest ... so all u get is a callback per step ala cucumber.js
. and good luck with ppl testing at this level of abstraction in javascript :) ... that's ultimately the biggest letdown for me

**Comment by noamtcohen** [comment]
I don't hate coffee I just don't understand its need. (as for TS)
It's ok that the callback is per step and it makes sense, I need the async functionality since most useful code in nodejs is async. What is ppl testing?
